### ISSUE TITLE
[Bug]: Limitations with Kitty navigation over SSH

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/smart-splits.nvim#103]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

n/a doesn't matter what version

### Multiplexer Integration

Wezterm and Kitty both affected

### Steps to Reproduce

1. Create split
2. SSH into a remote server and run nvim from the remote server in the split

### Expected Behavior

You can use the keymaps to navigate between Neovim split panes.

### Actual Behavior

You can't because the pane does not report the remote foreground process name, so the keymaps can't check if nvim is running in the pane.

### Minimal Configuration to Reproduce

```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme! it makes testing nicer
  'folke/tokyonight.nvim',
  'mrjones2014/smart-splits.nvim',
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

require('smart-splits').setup({
  -- add any options here
})

-- recommended mappings
-- resizing splits
-- these keymaps will also accept a range,
-- for example `10<A-h>` will `resize_left` by `(10 * config.default_amount)`
vim.keymap.set('n', '<A-h>', require('smart-splits').resize_left)
vim.keymap.set('n', '<A-j>', require('smart-splits').resize_down)
vim.keymap.set('n', '<A-k>', require('smart-splits').resize_up)
vim.keymap.set('n', '<A-l>', require('smart-splits').resize_right)
-- moving between splits
vim.keymap.set('n', '<C-h>', require('smart-splits').move_cursor_left)
vim.keymap.set('n', '<C-j>', require('smart-splits').move_cursor_down)
vim.keymap.set('n', '<C-k>', require('smart-splits').move_cursor_up)
vim.keymap.set('n', '<C-l>', require('smart-splits').move_cursor_right)
-- swapping buffers between windows
vim.keymap.set('n', '<leader><leader>h', require('smart-splits').swap_buf_left)
vim.keymap.set('n', '<leader><leader>j', require('smart-splits').swap_buf_down)
vim.keymap.set('n', '<leader><leader>k', require('smart-splits').swap_buf_up)
vim.keymap.set('n', '<leader><leader>l', require('smart-splits').swap_buf_right)

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme! it makes testing nicer
vim.cmd([[colorscheme tokyonight]])
```

### Additional Details and/or Screenshots

This appears to be a limitation in the multiplexer of Wezterm and Kitty.

#### Wezterm

> **Note**
> Issue has been resolved for Wezterm by #105 

[pane:get_foreground_process_name()](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html?h=get_foreground_process_name):

> This information is only available for local panes. Multiplexer panes do not report this information. Similarly, if you are using eg: ssh to connect to a remote host, you won't be able to access the name of the remote process that is running.

Opened discussion: https://github.com/wez/wezterm/discussions/3648

#### Kitty

Opened discussion: https://github.com/kovidgoyal/kitty/discussions/6229

**Comment by mrjones2014** [comment]
cc @phgz

**Comment by mrjones2014** [comment]
Edited issue to indicate that it is solved for Wezterm

**Comment by mrjones2014** [comment]
Kitty added user var support.

**Comment by mrjones2014** [comment]
I believe this is fixed by #175

**Comment by AniAggarwal** [comment]
This unfortunately still does not work for me using the steps outlined in the readme, nor with a large assortment of options I tried. 
What should I be doing to connect over ssh? Should I be using the ssh kitten? Also, should I be using the -R flag to set up some sort of forwarding? And should I set the `forward_remote_control` option? I see the readme says to use `/tmp/mykitty`  but the documentation for truly convenient ssh says that abstract sockets don't work. 

Sorry about all the questions; no combinations of those above options seemed to work for my use case.

I have kitty + nvim installed on local and remote machine. I also have identical nvim and kitty configs on both ends. 
I am able to create a split and then kitten ssh to my remote machine and enter nvim. But, I cannot switch from nvim across a kitty split. I can go the other way. 
SmartSplitLog shows that it detects kitty backend.

If I ssh without the kitten then no backend is detected and I can switch across kitty splits but cannot switch within nvim splits (i.e. instead of moving between the two splits in the nvim window, it will move to a different kitty window).

Let me know what I can do help debug!

**Comment by mrjones2014** [comment]
I'm not too sure unfortunately. I don't use Kitty, a lot of the kitty support stuff has come from community contributions. First thing I would check is if you're on the latest version of Kitty (or at least one that supports user variables). 

Perhaps some other Kitty users could chime in here. @phgz @oddnugget does it work for you in Kitty? Are you using the SSH Kitten or regular `ssh` command?

> And should I set the `forward_remote_control` option? 

That could possibly be the issue, try setting that and see if it works.

> abstract sockets don't work

Not too sure what you mean by "abstract" sockets. Could you drop a link to the documentation in question?

**Comment by AniAggarwal** [comment]
Thanks for making and maintaining this plugin! I unfortunately haven't been able to meaningfully debug since I don't have a great understanding of sockets. I'll try to take some time over the next few days and learn how this works and maybe I'll find the issue myself or at least be able to provide more meaningful debugging outputs. 

I believe the abstract sockets refers to using `@mykitty` as a socket rather than `/tmp/mykitty`, from [this](https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.forward_remote_control) documentation. [Here's](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.allow_remote_control) some more details on it.

Here's a discussion on the Kitty side trying to debug the kitty side. 
https://github.com/kovidgoyal/kitty/discussions/5891#discussioncomment-9852795

I can confirm that the plugin works as expected following the steps in the above discussion post when ssh'd to localhost, but not while ssh'd to a remote host.

**Comment by oddnugget** [comment]
> Perhaps some other Kitty users could chime in here. @phgz @oddnugget does it work for you in Kitty? Are you using the SSH Kitten or regular ssh command?

I'm using the `kitten ssh` command with the `allow_remote_control yes` and `listen_on unix:/tmp/mykitty` set in the kitty config. I also have a `/kitty/ssh.conf` with the host alias and `forward_remote_control yes` set for that host. 

There was a lot of trial and error that eventually led to me getting it working, so im not certain which configs are necessary.

**Comment by mrjones2014** [comment]
I'm guessing that `forward_remote_control yes` is needed. @oddnugget  are you on Linux or macOS?

I'm wondering if both Linux and macOS need to use `unix:/tmp/mykitty` style socket path since abstract sockets (`@mykitty`) won't work.

**Comment by oddnugget** [comment]
> I'm guessing that `forward_remote_control yes` is needed. @oddnugget are you on Linux or macOS?
> 
> I'm wondering if both Linux and macOS need to use `unix:/tmp/mykitty` style socket path since abstract sockets (`@mykitty`) won't work.

Im on macOS

**Comment by AniAggarwal** [comment]
I am unfortunately also on Mac OS and have a similar config.  I am able to recreate the issue with [these](https://github.com/kovidgoyal/kitty/discussions/5891#discussioncomment-9861906) steps every time. 
When using the exact setup you have just mentioned I still run into the same issue of being able to nagivate within neovim but not across kitty windows.

Smart Splits does indeed detect the kitty backend.
Using kitten ssh with the `-v` command shows the ports are being allocated/forwarded correctly.
I tried setting the log level to trace but wasn't able to get any output. What else can I do to debug this? It seems like the kitty side is working.

**Comment by mrjones2014** [comment]
Sorry for the delay. It's been crazy at my day job.

> I tried setting the log level to trace but wasn't able to get any output.

In smart-splits.nvim or in Kitty? If you set the log level like so

```lua
require('smart-splits').setup({ log_level = 'trace' })
```

you should definitely be getting logs in `:SmartSplitsLog` so that's strange 🤔

**Comment by ch4xer** [comment]
Same error here on arch linux.

kitty version: 0.39.1
neovim version: v0.10.4

The configuration of smart-splits.nvim:

```lua
  {
    "mrjones2014/smart-splits.nvim",
    build = "./kitty/install-kittens.bash",
    lazy = false,
    config = function()
      require("smart-splits").setup({ log_level = "trace" })
    end,
    -- stylua: ignore
    keys = {
      { "<C-h>", function() require("smart-splits").move_cursor_left() end, desc = "focus leftside window", },
      { "<C-j>", function() require("smart-splits").move_cursor_down() end, desc = "focus downside window", },
      { "<C-k>", function() require("smart-splits").move_cursor_up() end, desc = "focus upside window", },
      { "<C-l>", function() require("smart-splits").move_cursor_right() end, desc = "focus rightside window", },
    },
  },
```

The configuration of kitty:

```
allow_remote_control yes
forward_remote_control yes
listen_on unix:@mykitty

clipboard_control write-clipboard write-primary read-clipboard read-primary

enabled_layouts grid,stack
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{' ' + title[title.rfind(' ')+1:] if (title.startswith('nvim ')) else title[title.rfind('/')+1:]}"

clear_all_shortcuts			yes
map ctrl+v paste_from_clipboard
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

map ctrl+n new_os_window_with_cwd

map ctrl+enter new_window_with_cwd
map ctrl+w close_window
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down
# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l
```

The smart-splits.nvim works fine without ssh, with the output `[smart-splits.nvim] Auto-detected multiplexer back-end: kitty`. However, the plugin didn't work under ssh senorio, with the output `[smart-splits.nvim] Auto-detected multiplexer back-end: none`.

**Comment by ch4xer** [comment]
This issue still exists with kitty 0.45.0, NVIM v0.11.5 and smart-splits.nvim (fdd63c5)

**Comment by maatthc** [comment]
> This issue still exists with kitty 0.45.0, NVIM v0.11.5 and smart-splits.nvim ([fdd63c5](https://github.com/mrjones2014/smart-splits.nvim/commit/fdd63c566e760f14d9390d43d5dc6bf6eea5a07b))

Please share your Kitty and nvim configs @ch4xer . Are you using any terminal multiplexer?

**Comment by ch4xer** [comment]
> Same error here on arch linux. The configurations of kitty and neovim are identical on both ends.
> 
> kitty version: 0.39.1
> neovim version: v0.10.4
> 
> The configuration of smart-splits.nvim:
> 
> ```lua
>   {
>     "mrjones2014/smart-splits.nvim",
>     build = "./kitty/install-kittens.bash",
>     lazy = false,
>     config = function()
>       require("smart-splits").setup({ log_level = "trace" })
>     end,
>     -- stylua: ignore
>     keys = {
>       { "<C-h>", function() require("smart-splits").move_cursor_left() end, desc = "focus leftside window", },
>       { "<C-j>", function() require("smart-splits").move_cursor_down() end, desc = "focus downside window", },
>       { "<C-k>", function() require("smart-splits").move_cursor_up() end, desc = "focus upside window", },
>       { "<C-l>", function() require("smart-splits").move_cursor_right() end, desc = "focus rightside window", },
>     },
>   },
> ```
> 
> The configuration of kitty:
> 
> ```
> allow_remote_control yes
> forward_remote_control yes
> listen_on unix:@mykitty
> 
> clipboard_control write-clipboard write-primary read-clipboard read-primary
> 
> enabled_layouts grid,stack
> tab_bar_edge top
> tab_bar_style powerline
> tab_powerline_style slanted
> tab_title_template "{' ' + title[title.rfind(' ')+1:] if (title.startswith('nvim ')) else title[title.rfind('/')+1:]}"
> 
> clear_all_shortcuts			yes
> map ctrl+v paste_from_clipboard
> map ctrl+equal change_font_size all +2.0
> map ctrl+minus change_font_size all -2.0
> 
> map ctrl+n new_os_window_with_cwd
> 
> map ctrl+enter new_window_with_cwd
> map ctrl+w close_window
> map ctrl+h neighboring_window left
> map ctrl+l neighboring_window right
> map ctrl+k neighboring_window up
> map ctrl+j neighboring_window down
> # Unset the mapping to pass the keys to neovim
> map --when-focus-on var:IS_NVIM ctrl+j
> map --when-focus-on var:IS_NVIM ctrl+k
> map --when-focus-on var:IS_NVIM ctrl+h
> map --when-focus-on var:IS_NVIM ctrl+l
> ```
> 
> The smart-splits.nvim works fine without ssh, with the output `[smart-splits.nvim] Auto-detected multiplexer back-end: kitty`. However, the plugin didn't work under ssh senorio, with the output `[smart-splits.nvim] Auto-detected multiplexer back-end: none`.
> 
> 

@maatthc this is my config, and i'm not using tmux or other 
terminal multiplexer.

**Comment by maatthc** [comment]
Thanks!
I think the problem would be: `listen_on unix:/tmp/mykitty` - **tmp** instead of **@**.

I've added a new session to the docs spefically for [Kitty+ssh](https://github.com/mrjones2014/smart-splits.nvim?tab=readme-ov-file#nvim-over-ssh-with-kitty) but the 'normal' session is still not up to date.

I will add a small change to sync it. 

Meanwhile, could you please give it a try with the instructions for ssh?

**Comment by ch4xer** [comment]
> Thanks! I think the problem would be: `listen_on unix:/tmp/mykitty` - **tmp** instead of **@**.
> 
> I've added a new session to the docs spefically for [Kitty+ssh](https://github.com/mrjones2014/smart-splits.nvim?tab=readme-ov-file#nvim-over-ssh-with-kitty) but the 'normal' session is still not up to date.
> 
> I will add a small change to sync it.
> 
> Meanwhile, could you please give it a try with the instructions for ssh?

Thanks for the reply, but it still doesn’t work.
Are you able to reproduce this successfully when using kitty over SSH?
If you have a configuration repository that I could refer to, it would be greatly appreciated.

**Comment by maatthc** [comment]
@ch4xer , I'm using my own fork to test some upcoming Kitty enhancements that I’ll be upstreaming soon. Everything else follows the standard configuration.

```
	{
		"maatthc/fork-smart-splits.nvim",
		lazy = false,
		opts = { default_amount = 20, at_edge = "stop" },
	},
``` 
Have you added `forward_remote_control yes` to `~/.config/kitty/ssh.conf`?

Are you using `kitten ssh` when connecting to the remote host?

**Comment by mrjones2014** [comment]
> Are you using `kitten ssh` when connecting to the remote host?

Oh yeah this is important, I forgot about that. Just like with Wezterm you have to use `wezterm ssh`.

**Comment by ch4xer** [comment]
@maatthc @mrjones2014 I sincerely apologize for the inconvenience. The root cause was that I mistakenly put `forward_remote_control yes` in `kitty.conf` rather than in `ssh.conf`. After correcting this, everything is now functioning as expected. Thank you for your patience and tolerance.

**Comment by maatthc** [comment]
No worries @ch4xer, I'm glad it is working 🥳
